config/routes.rb
Rails.application.routes.draw do
  resources :pdfs
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/pdf.rb
class Pdf < ApplicationRecord
  has_one_attached :pdf_file
  belongs_to :owner, class_name: 'User'
  belongs_to :uploaded_by, class_name: 'User'
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :username, with: ->(e) { e.strip }
  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  before_action :set_pdf, only: %i[ show edit update destroy ]

  # GET /pdfs or /pdfs.json
  def index
    @pdfs = Pdf.all
  end

  # GET /pdfs/1 or /pdfs/1.json
  def show
  end

  # GET /pdfs/new
  def new
    @pdf = Pdf.new
  end

  # GET /pdfs/1/edit
  def edit
  end

  # POST /pdfs or /pdfs.json
  def create
    @pdf = Pdf.new(pdf_params)
    pdf_file = params["pdf_file"]
    @pdf.owner = @pdf.uploaded_by = Current.user
    @pdf.uploaded_filename = pdf_file.original_filename
    @pdf.uploaded_at = DateTime.now
    @pdf.page_count = 42
    p "!!! @pdf #{@pdf.inspect} pdf_file #{@pdf.pdf_file.inspect}"

    respond_to do |format|
      if @pdf.save
        format.html { redirect_to @pdf, notice: "Pdf was successfully created." }
        format.json { render :show, status: :created, location: @pdf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pdfs/1 or /pdfs/1.json
  def update
    respond_to do |format|
      if @pdf.update(pdf_params)
        format.html { redirect_to @pdf, notice: "Pdf was successfully updated." }
        format.json { render :show, status: :ok, location: @pdf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdfs/1 or /pdfs/1.json
  def destroy
    @pdf.destroy!

    respond_to do |format|
      format.html { redirect_to pdfs_path, status: :see_other, notice: "Pdf was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pdf
      @pdf = Pdf.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def pdf_params
      params.expect(pdf: [ :name, :owner_id, :version, :description, :pdf_file, :page_count, :first_page_number,
                           :uploaded_filename, :uploaded_at, :uploaded_by_id ])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Pudding"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
  %body
    = yield

app/views/pdfs/_form.html.haml
= form_with(model: pdf) do |form|
  - if pdf.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(pdf.errors.count, "error")
        prohibited this pdf from being saved:
      %ul
        - pdf.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name
  %div
    = form.label :version, style: "display: block"
    = form.text_field :version
  %div
    = form.label :description, style: "display: block"
    = form.text_field :description
  %div
    = form.label :pdf_file, style: "display: block"
    = form.file_field :pdf_file
  %div
    = form.label :first_page_number, style: "display: block"
    = form.text_field :first_page_number
  %div
    = form.submit

app/views/pdfs/_pdf.html.haml
%div{:id => "#{dom_id pdf}"}
  %p
    %strong Name:
    = pdf.name
  %p
    %strong Owner:
    = pdf.owner_id
  %p
    %strong Version:
    = pdf.version
  %p
    %strong Description:
    = pdf.description
  %p
    %strong Page count:
    = pdf.page_count
  %p
    %strong First page numberuploaded filename:
    = pdf.first_page_numberuploaded_filename
  %p
    %strong Uploaded at:
    = pdf.uploaded_at
  %p
    %strong Uploaded by:
    = pdf.uploaded_by_id

app/views/pdfs/edit.html.haml
- content_for :title, "Editing pdf"
%h1 Editing pdf
= render "form", pdf: @pdf
%br/
%div
  = link_to "Show this pdf", @pdf
  |
  \#{link_to "Back to pdfs", pdfs_path}

app/views/pdfs/index.html.haml
%p{:style => "color: green"}= notice
- content_for :title, "Pdfs"
%h1 Pdfs
#pdfs
  - @pdfs.each do |pdf|
    = render pdf
    %p
      = link_to "Show this pdf", pdf
= link_to "New pdf", new_pdf_path

app/views/pdfs/new.html.haml
- content_for :title, "New pdf"
%h1 New pdf
= render "form", pdf: @pdf
%br/
%div
  = link_to "Back to pdfs", pdfs_path

app/views/pdfs/show.html.haml
%p{:style => "color: green"}= notice
= render @pdf
%div
  = link_to "Edit this pdf", edit_pdf_path(@pdf)
  |
  \#{link_to "Back to pdfs", pdfs_path}
  
  \#{button_to "Destroy this pdf", @pdf, method: :delete}